[package]
name = "qas-macro"
version = "0.0.0"
authors = ["Roman <romann.tarasenko@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
peg = "0.7.0"
check_keyword = "0.1.1"
chrono = "0.4.19"
bitflags = "1.3.2"
bit-vec = "0.6.3"
